name:                hapi
version:             0.1.0.0
github:              "githubuser/hapi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# extra-include-dirs:
#   - ./test/test-api/broken-arith
# extra-lib-dirs:
#   - ./test/test-api/broken-arith
# extra-libraries: broken-arith

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hapi#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2
- random >= 1.2.0
- fused-effects >= 1.1.1.1
- QuickCheck >= 2.14.2
- quickcheck-transformer >= 0.3.1.1
- HList >= 0.5.0.0
- grpc-haskell >= 0.1.0

library:
  source-dirs: src
  c-sources:
    - ./test/test-api/broken-arith/broken-arith.c

executables:
  hapi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hapi

tests:
  hapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hapi
